name: Deploy Rust Project Based on Tag

on:
  push:
    branch:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Navigate Into ws-server Directory
        run: cd ws-server

      - name: Install dependencies
        run: cargo build --release

      - name: Determine environment
        id: determine-env

      - name: Run tests
        run: cargo test --release

      - name: Run clippy
        run: cargo clippy --release

      - name: Print hooray
        run: each "Hooray!"