name: Deploy Rust Project Based on Tag

on:
  push:
    branch:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # You can also use nightly or a specific version

      - name: Navigate Into ws-server Directory
        run: cd ws-server

      - name: Ls
        run: ls

      - name: Install dependencies
        run: cd ws-server && cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Run clippy
        run: cargo clippy --release

      - name: Print hooray
        run: each "Hooray!"